### ISSUE TITLE
Support in a Bootstrap modal

### ISSUE THREAD

**Issue by marty912** [DanielYKPan/ng2-date-time-picker#8]
Hello, 

I wanted to use the component in a Bootstrap 3 modal but I had some problems. 
First, I tried to use it in the default mode ('popup') but it wasn't very good looking.
Then I used the 'dropdown' mode and I had a position problem caused by the fixed position (CSS) of the Bootstrap modal. 

I have found a workaround : set the position of the modal to absolute but maybe you have a better idea to soluce this problem. 

Thanks, 

Marty

**Comment by DanielYKPan** [comment]
I haven't try this package with Bootstrap yet. I will have a look at it.

**Comment by DanielYKPan** [comment]
@marty912 
I guess the problem is my HTML class names are too general, and the bootstrap css has effect on my module. I would rename those name, and you could update the latest version. It should be all right.

**Comment by marty912** [comment]
@DanielYKPan 
I don't think it's a clash of CSS rules. 
[https://github.com/DanielYKPan/ng2-date-time-picker/blob/master/src/lib/dialog.component.ts#L176](url) : in this method, you are looking for a parent with a position fixed and, in my case, the method found the Bootstrap Modal and set the dropdown position with a gap compared to the original input. 

Hope this will help !

**Comment by DanielYKPan** [comment]
@marty912 
I got it. The problem is the bootstrap modal has a CSS declaration of  webkit-transform: translate3d(0,0,0). The transform declaration changes the positioning context from the viewport to the rotated element, which essentially means that my fixed element behaves as if it were absolutely positioned. This all mess up my dropdown picker position.

 You could find more inform form [this](http://stackoverflow.com/questions/25824749/why-webkit-transform-translate3d0-0-0-messes-up-with-fixed-childs) and [this](http://stackoverflow.com/questions/36855473/position-fixed-not-working-is-working-like-absolute)

**Comment by marty912** [comment]
Yes, it works perfectly in a Modal now ! Thanks ! 😄
